# Generated by Django 3.1.4 on 2021-01-12 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=20)),
                ('subject', models.CharField(default='', max_length=30)),
                ('message', models.TextField(default='')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsive', models.CharField(default='', max_length=15)),
                ('template', models.CharField(default='', max_length=5)),
                ('type', models.CharField(default='', max_length=15)),
                ('design', models.CharField(default='', max_length=20)),
                ('pages', models.CharField(default='', max_length=5)),
                ('database', models.CharField(default='', max_length=5)),
                ('api', models.CharField(default='', max_length=5)),
                ('name', models.CharField(default='', max_length=30)),
                ('contact', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('message', models.TextField(default='')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Web_Mobile_Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsive', models.CharField(default='', max_length=15)),
                ('template', models.CharField(default='', max_length=5)),
                ('technologies', models.CharField(default='', max_length=20)),
                ('type', models.CharField(default='', max_length=15)),
                ('design', models.CharField(default='', max_length=20)),
                ('pages', models.CharField(default='', max_length=5)),
                ('apptype', models.CharField(default='', max_length=15)),
                ('name', models.CharField(default='', max_length=30)),
                ('contact', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('message', models.TextField(default='')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Website_Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsive', models.CharField(default='', max_length=15)),
                ('template', models.CharField(default='', max_length=5)),
                ('type', models.CharField(default='', max_length=15)),
                ('design', models.CharField(default='', max_length=20)),
                ('pages', models.CharField(default='', max_length=5)),
                ('technologies', models.CharField(default='', max_length=10)),
                ('name', models.CharField(default='', max_length=30)),
                ('contact', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('message', models.TextField(default='')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
