# Generated by Django 3.1.4 on 2021-03-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rohartech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('category', models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Product', 'Product')], max_length=15, null=True)),
                ('show', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
